# Generated by Django 5.0.6 on 2024-11-20 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('front_img', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('back_img', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('dell', 'Dell'), ('hp', 'HP'), ('accessory', 'Accessory'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=50, null=True)),
                ('product_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
